/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  privateSidebar: [
    'events/intro',
    {
      type: 'category',
      label: '🎊 Events',
      link: {
        type: 'generated-index',
        title: '🎊 Events',
        description: 'All pages dedicated to details about events that have been held or are in progress.',
        slug: '/events',
      },
      collapsed: false,
      items: ['events/zombies', 'events/egghunt2', 'events/egghunt'],
    },
    {
      type: 'html',
      value: '<div style="margin: var(--ifm-hr-margin-vertical-side)">',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: '🕹️ Modded',
      link: {
        type: 'generated-index',
        title: '🕹️ Modded',
        description: 'All pages dedicated to the details of modded servers.',
        slug: '/modded',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '🏰 Fantasy Medieval',
          link: {
            type: 'generated-index',
            title: '🏰 Fantasy Medieval',
            description: 'All pages dedicated to the details of the Fantasy Medieval server.',
            slug: '/modded/fantasymedieval',
          },
          collapsed: false,
          items:[
            {
              type: 'doc',
              id: 'modded/fantasymedieval/start',
              label: '🏰 Начать игру',
            },
            {
              type: 'doc',
              id: 'modded/fantasymedieval/mods',
              label: '🛠️ Список модов',
            },
            {
              type: 'doc',
              id: 'modded/fantasymedieval/commands',
              label: '💻 Команды',
            },
          ],
        },
        {
          type: 'category',
          label: '🍇 FreshIndustrial',
          link: {
            type: 'generated-index',
            title: '🍇 FreshIndustrial',
            description: 'All pages dedicated to the details of the FreshIndustrial server.',
            slug: '/modded/freshindustrial',
          },
          collapsed: true,
          items:[
            {
              type: 'doc',
              id: 'modded/freshindustrial/start',
              label: '🍇 Начать игру',
            },
            {
              type: 'doc',
              id: 'modded/freshindustrial/faq',
              label: '❓ FAQ',
            },
            {
              type: 'doc',
              id: 'modded/freshindustrial/servermods',
              label: '🔐 Серверные моды',
            },
            {
              type: 'doc',
              id: 'modded/freshindustrial/clientmods',
              label: '🛠️ Клиентские моды',
            },
            {
              type: 'doc',
              id: 'modded/freshindustrial/commands',
              label: '💻 Команды',
            },
          ],
        },
      ],
    },
  ],

  publicSidebar: [
    'plugins/intro',
    {
      type: 'category',
      label: '🧩 Plugins',
      link: {
        type: 'generated-index',
        title: '🧩 Plugins',
        description: 'All pages dedicated to details about my plugins.',
        slug: '/plugins',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '🧟 EastZombies',
          collapsed: false,
          items:[
            {
              type: 'doc',
              id: 'plugins/eastzombies/intro',
              label: '🧟 Intro',
            },
            {
              type: 'doc',
              id: 'plugins/eastzombies/commands',
              label: '🧟 Commands',
            },
            {
              type: 'doc',
              id: 'plugins/eastzombies/configuration',
              label: '🧟 Configuration',
            },
            {
              type: 'doc',
              id: 'plugins/eastzombies/faq',
              label: '🧟 FAQ',
            },
          ],
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
